In [1]:
import numpy as np


In [3]:
np.set_printoptions(precision=2)
# 프린터 할때 피리시즌 표시 변경

In [4]:
M=np.random.normal(0,1,(2,3))

In [5]:
print(M)

[[-0.37 -1.07 -1.36]
 [-1.26 -1.78 -0.29]]


In [6]:
n=np.sum(M)

In [8]:
print(n.round(2))

-6.13


In [12]:
#set data params

n_student,n_class=500,5
means=np.random.randint(40,60,(n_class,))
stds=np.random.uniform(5,10,(n_class,))

scores=np.random.normal(loc=means,scale=stds,size=(n_student,n_class))


In [13]:
print(f'mean setting:\n  {means}')
print(f'std setting:\n {stds}')

mean setting:
 
 [56 58 46 55 51]
std setting:
 [9.74 5.65 6.1  5.59 9.14]


In [14]:
print('means:',np.mean(scores,axis=0))
print('stds:',np.std(scores,axis=0))


means: [56.69 57.93 45.85 54.99 50.71]
stds: [9.91 5.58 5.89 5.65 9.1 ]


In [16]:
print('max:',scores.max(axis=0))
print('min',np.amin(scores,axis=0))

max: [92.32 73.6  63.44 79.49 72.44]
min [20.23 39.82 27.76 38.12 16.58]


In [17]:
#min_max_normalization
scores_min_max_nor=(scores-scores.min(axis=0,keepdims=True))/(scores.max(axis=0,keepdims=True)-scores.min(axis=0,keepdims=True)) 

In [18]:
scores_min_max_nor.shape

(500, 5)

In [20]:
print(scores_min_max_nor.mean(axis=0))
print(scores_min_max_nor.min(axis=0))
print(scores_min_max_nor.max(axis=0))


[0.51 0.54 0.51 0.41 0.61]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [21]:
scores_standard=(scores-scores.mean(axis=0,keepdims=True))/scores.std(axis=0,keepdims=True)

In [22]:
scores_standard.mean(axis=0)

array([-1.92e-15,  1.70e-14, -4.12e-15,  3.14e-15, -4.33e-15])

In [23]:
scores_standard.std(axis=0)

array([1., 1., 1., 1., 1.])

In [26]:
from termcolor import colored

In [28]:
M_scores=scores.max(axis=0)
m_scores=scores.min(axis=0)
print(colored('before m-M normalization','green'))


before m-M normalization


In [29]:
import numpy as np
np.set_printoptions(precision=2)
means=scores.mean(axis=0)
stds=scores.std(axis=0)
print(colored('before','green'))

before


In [34]:
n_student=10
scores=np.random.randint(0,100,(n_student,))
print(scores.shape,scores)
cutoff=np.array([20,40,60,80]).reshape(-1,1)


(10,) [32  7 95 47 47 92 11 63 64  4]


In [38]:
scores_grade=np.where(scores<cutoff[0],0,np.where(scores<cutoff[1],1,np.where(scores<cutoff[2],2,np.where(scores<cutoff[3],3,4))))

In [39]:
scores_grade

array([1, 0, 4, 2, 2, 4, 0, 3, 3, 0])

In [41]:
scores=scores.reshape(-1,1)
cutoff=cutoff.reshape(1,-1)
print(scores.shape,cutoff.shape)

(10, 1) (1, 4)


In [47]:
grade= (scores>cutoff).astype(np.int8).sum(axis=1).reshape(-1,1)
print(grade)
scores_grade=np.hstack([scores,grade])
print(scores_grade)

[[1]
 [0]
 [4]
 [2]
 [2]
 [4]
 [0]
 [3]
 [3]
 [0]]
[[32  1]
 [ 7  0]
 [95  4]
 [47  2]
 [47  2]
 [92  4]
 [11  0]
 [63  3]
 [64  3]
 [ 4  0]]
