In [3]:
import numpy as np
from termcolor import colored

np.printoptions(precision=2)

In [9]:
n_element=4
u=np.random.uniform(0,10,(n_element,))
v=np.random.uniform(0,10,(n_element,))
print(colored((u,v),'green' ))

u_len=np.sqrt(np.sum(np.square(u)))
v_len=np.sqrt(np.sum(np.square(v)))
print(u_len,v_len)

(array([8.34245061, 7.6860489 , 1.5131404 , 2.11706578]), array([5.81289064, 2.81280237, 4.78204692, 5.53970822]))
11.638014918063869 9.760015098872453


In [10]:
u_unit=u/u_len
v_unit=v/v_len
print(u_unit,v_unit)


[0.71682763 0.66042611 0.13001705 0.18190953] [0.59558214 0.28819652 0.48996307 0.56759218]


In [14]:
n_vector,n_element=3,4
U=np.random.uniform(0,10,(n_vector,n_element))
U_len=np.sqrt(np.sum(np.square(U),axis=1))

In [16]:
U_unit=U/U_len.reshape(-1,1)

In [18]:
U_unit_len=np.sum(np.square(U_unit),axis=1)
print(U_unit_len)

[1. 1. 1.]


In [21]:
import numpy as np
np.printoptions(precision=2)
n_element=4
u=np.random.uniform(0,10,(n_element,))
v=np.random.uniform(0,10,(n_element,))
print(u.shape,v.shape)
distance=np.sqrt(np.sum(np.square(u-v)))
print('euclidean distance',distance)

(4,) (4,)
euclidean distance 7.810982330179535


In [23]:
import numpy as np
np.printoptions(precision=2)
n_vector,n_element=3,4
u=np.random.uniform(0,10,(n_vector,n_element))
v=np.random.uniform(0,10,(n_vector,n_element))
distance=np.sqrt(np.sum(np.square(u-v),axis=1))
print(distance)

[9.11879416 6.74235411 9.07046658]


In [25]:
import numpy as np
np.printoptions(precition=2)
n_vector1,n_vector2=3,4
n_element=4
U=np.random.uniform(0,10,(n_vector1,n_element))
V=np.random.uniform(0,10,(n_vector2,n_element))
U_=np.expand_dims(U,0)
V_=np.expand_dims(V,1)
print(U_.shape,V_.shape)

(1, 3, 4) (4, 1, 4)


In [31]:
print(U_,'\n',V_)
print(U_-V_)

[[[0.28075659 8.66689037 3.92154527 1.04589115]
  [3.12882165 0.31624476 1.76781601 2.65309737]
  [8.21282079 6.85413069 2.69149961 6.8989447 ]]] 
 [[[1.82370569 9.50245845 0.37102722 6.11003655]]

 [[7.71879165 5.49898696 7.50122926 2.860247  ]]

 [[9.41073299 8.29608051 0.88240515 4.58452966]]

 [[4.37282608 6.99787109 4.08825051 7.27709259]]]
[[[-1.54294909 -0.83556808  3.55051805 -5.0641454 ]
  [ 1.30511596 -9.18621368  1.39678879 -3.45693918]
  [ 6.38911511 -2.64832776  2.32047238  0.78890815]]

 [[-7.43803505  3.16790341 -3.57968399 -1.81435585]
  [-4.58997    -5.1827422  -5.73341324 -0.20714964]
  [ 0.49402914  1.35514372 -4.80972965  4.0386977 ]]

 [[-9.12997639  0.37080986  3.03914012 -3.53863851]
  [-6.28191134 -7.97983575  0.88541086 -1.93143229]
  [-1.19791219 -1.44194983  1.80909446  2.31441504]]

 [[-4.09206948  1.66901928 -0.16670524 -6.23120143]
  [-1.24400443 -6.68162633 -2.3204345  -4.62399522]
  [ 3.83999472 -0.1437404  -1.3967509  -0.37814789]]]


In [35]:

E_disatance_fully=np.sqrt(np.sum(np.square(U_-V_),axis=2))
print(E_disatance_fully)

[[ 6.42888893  9.99956484  7.33766992]
 [ 9.02585187  8.99130579  6.44399392]
 [10.25925456 10.37567211  3.48476006]
 [ 7.64109416  8.5415119   4.10610882]]


In [36]:
#manhatan distance
import numpy as np
np.printoptions(precition=2)


In [38]:
n_vector,n_element=2,2
u=np.random.uniform(0,10,(n_vector,n_element))
v=np.random.uniform(0,10,(n_vector,n_element))
print(u.shape,v.shape)
print(u,'\n \n',v)

(2, 2) (2, 2)
[[3.6923774  4.01660342]
 [9.35370363 6.44308567]] 
 
 [[1.72159259 9.990944  ]
 [8.42531432 9.05727749]]


In [39]:
m_dist=np.sum(np.abs(u-v),axis=1)
print(m_dist)

[7.94512539 3.54258114]


In [41]:
n_vector1,n_vector2=3,4
n_element=2
U=np.random.uniform(0,10,(n_vector1,n_element))
V=np.random.uniform(0,10,(n_vector2,n_element))
print(U.shape,V.shape)

(3, 2) (4, 2)


In [43]:
U_=np.expand_dims(U,0)
V_=np.expand_dims(V,1)
print(U_.shape,V_.shape)


(1, 3, 2) (4, 1, 2)


In [46]:
m_dist=np.sum(np.abs(U_-V_),axis=-1)
print(m_dist.shape)
print(m_dist)

(4, 3)
[[9.89154589 2.12342471 2.47720689]
 [2.52085627 7.99175943 9.84789651]
 [8.69877868 2.34828999 3.66997411]
 [5.78539958 4.72721612 6.5833532 ]]


In [50]:
#cosine similarity
import numpy as np
from termcolor import colored
np.printoptions(precision=2)
n_element=4
u=np.random.uniform(0,10,(n_element,))
v=np.random.uniform(0,10,(n_element,))
u_len=np.sqrt(np.sum(np.square(u)))
v_len=np.sqrt(np.sum(np.square(v)))
u_unit=u/u_len
v_unit=v/v_len
cos=np.sum(u_unit*v_unit)
print('cosine similarty',cos)

cosine similarty 0.8326352548464262


In [53]:
n_element=4
n_vector=3
U=np.random.uniform(0,10,(n_vector,n_element))
V=np.random.uniform(0,10,(n_vector,n_element))
U_len=np.sqrt(np.sum(np.square(U),axis=1)).reshape(-1,1)
V_len=np.sqrt(np.sum(np.square(V),axis=1)).reshape(-1,1)
U_unit=U/U_len
V_unit=V/V_len
cos_=np.sum(U_unit*V_unit,axis=1)
print(cos_)

[0.76359212 0.48772192 0.53641166]


In [55]:
n_vector1, n_vector2=3,4
n_element=4
U=np.random.uniform(0,10,(n_vector1,n_element))
V=np.random.uniform(0,10,(n_vector2,n_element))
U_len=np.sqrt(np.sum(np.square(U),axis=1).reshape(-1,1))
V_len=np.sqrt(np.sum(np.square(V),axis=1).reshape(-1,1))
U_unit=U/U_len
V_unit=V/V_len
U_unit_=np.expand_dims(U_unit,axis=0)
V_unit_=np.expand_dims(V_unit,axis=1)
cos_=np.sum(U_unit_*V_unit_,axis=-1)
print(cos_)

[[0.78894457 0.78307889 0.87577952]
 [0.97050874 0.88335193 0.90573533]
 [0.75117063 0.9748964  0.84860853]
 [0.81054417 0.58778802 0.85303773]]
