In [1]:
import numpy as np
a=np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[6 5 8 4 0 3 7 9 1 2]


In [2]:
# shuffle은 인프레이스 방식으로 적용

In [5]:
M=np.arange(15).reshape(5,-1)
print(M)
np.random.shuffle(M)
print(M)
N=np.arange(15).reshape(5,-1)
print(N)
N=N.T
np.random.shuffle(N)
N=N.T
print(N)
# 최외콱 차원으로 서플됨

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0  1  2]
 [ 9 10 11]
 [ 3  4  5]
 [ 6  7  8]
 [12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]
 [14 13 12]]


In [7]:
import numpy as np
from termcolor import colored
N=10

a=np.linspace(0,10,N)
b=np.linspace(0,100,N)
print(f'a: \n {a}\n')
print(f'b:\n {b}\n')

a: 
 [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]

b:
 [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]



In [8]:
indices=np.arange(N)
np.random.shuffle(indices)
a_shuffle=a[indices]
b_shuffle=b[indices]
print(a_shuffle)
print(b_shuffle)

[ 2.22222222  4.44444444  5.55555556  1.11111111  8.88888889  3.33333333
  7.77777778  0.          6.66666667 10.        ]
[ 22.22222222  44.44444444  55.55555556  11.11111111  88.88888889
  33.33333333  77.77777778   0.          66.66666667 100.        ]


In [11]:
N,n_feature=6,5
n_class=100
x_data=np.random.normal(0,1,(N,n_feature))
y_data=np.random.randint(0,n_class,(N,))
print(x_data.shape,y_data.shape)
indices=np.arange(N)
np.random.shuffle(indices)
print(x_data)
print(y_data)
print()
x_data_shuffle=x_data[indices]
y_data_shuffle=y_data[indices]
print(x_data_shuffle)
print(y_data_shuffle)

(6, 5) (6,)
[[ 0.12721744  1.24021887 -0.20077451  0.34866865  0.4070192 ]
 [-1.25135084 -0.765834    0.03203312  1.22513241 -0.28458978]
 [-0.05017186  0.09896153 -1.75501996  0.84357416  2.45810919]
 [-0.02264226 -0.70359442  1.67876108  0.2192411   0.30930094]
 [-0.67124248  0.63112781  2.59174859  0.17737638  0.70008471]
 [ 0.97397576  1.65801753  0.85050192 -0.84649877 -0.10325345]]
[67 36  6 88 94 44]

[[-0.67124248  0.63112781  2.59174859  0.17737638  0.70008471]
 [ 0.97397576  1.65801753  0.85050192 -0.84649877 -0.10325345]
 [-1.25135084 -0.765834    0.03203312  1.22513241 -0.28458978]
 [ 0.12721744  1.24021887 -0.20077451  0.34866865  0.4070192 ]
 [-0.02264226 -0.70359442  1.67876108  0.2192411   0.30930094]
 [-0.05017186  0.09896153 -1.75501996  0.84357416  2.45810919]]
[94 44 36 67 88  6]


In [12]:
N,n_featrue=200,5
n_class=100
batch_size=32
iters=8
x_data=np.random.normal(0,1,(N,n_featrue))
y_data=np.random.randint(0,n_class,N)
for iter in range(iters):
    indices=np.arange(N)
    np.random.shuffle(indices)
    batch_indices=indices[:batch_size]
    x_batch=x_data[batch_indices]
    y_batch=y_data[batch_indices]
    print(iter)
    print(x_batch.shape,y_batch.shape)

0
(32, 5) (32,)
1
(32, 5) (32,)
2
(32, 5) (32,)
3
(32, 5) (32,)
4
(32, 5) (32,)
5
(32, 5) (32,)
6
(32, 5) (32,)
7
(32, 5) (32,)


In [15]:
N,n_featrue=200,5
n_class=100
batch_size=32
iters=8
x_data=np.random.normal(0,1,(N,n_featrue))
y_data=np.random.randint(0,n_class,N)
indices=np.arange(N)
np.random.shuffle(indices)


for iter in range(iters):
    batch_indices=indices[batch_size*iter:batch_size*(iter+1)]
    x_batch=x_data[batch_indices]
    y_batch=y_data[batch_indices]
    print(iter)
    print(x_batch.shape,y_batch.shape)

0
(32, 5) (32,)
1
(32, 5) (32,)
2
(32, 5) (32,)
3
(32, 5) (32,)
4
(32, 5) (32,)
5
(32, 5) (32,)
6
(8, 5) (8,)
7
(0, 5) (0,)


In [1]:
dir()

['In',
 'Out',
 '_',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__vsc_ipynb_file__',
 '_dh',
 '_i',
 '_i1',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'exit',
 'get_ipython',
 'os',
 'quit',
 'site',
 'sys']